language: rust
rust:
  - stable
  - beta
  - nightly
install:
  - rustup toolchain install nightly-2018-05-07
  - rustup component add rustfmt-preview --toolchain nightly-2018-05-07
script:
  - cargo +nightly-2018-05-07 fmt -- --write-mode=diff
  - RUST_BACKTRACE=1 cargo test --verbose
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
cache: cargo
git:
  depth: 1
